# Generated by Django 2.0.5 on 2022-07-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
